apiVersion: v1
kind: Secret
metadata:
  name: enterprise-inventory-secret
  namespace: enterprise-inventory
type: Opaque
stringData:
  POSTGRES_PASSWORD: change-me
  APP_JWT_SECRET: change-me-super-secret-jwt-key-change-me-super-secret-jwt-key
